wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1652846636
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      4: 3.7.9
      5: 0.12.16
      8:
      - 3
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 4
img_scale:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 1.0e-05
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.2
